[project]
name = "stream-zip-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["obstore>=0.6", "stream-zip>=0.0.83"]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
