from typing import List

from ._buffer import Buffer
from .store import ObjectStore

def open(store: ObjectStore, path: str) -> ReadableFile:
    """Open a file object from the specified location.

    Args:
        store: The ObjectStore instance to use.
        path: The path within ObjectStore to retrieve.

    Returns:
        ReadableFile
    """

async def open_async(store: ObjectStore, path: str) -> AsyncReadableFile:
    """Call `open` asynchronously.

    Refer to the documentation for [open][object_store_rs.open].
    """

class ReadableFile:
    def close(self) -> None: ...
    def read(self, size: int | None = None, /) -> Buffer: ...
    def readall(self) -> Buffer: ...
    def readline(self) -> Buffer: ...
    def readlines(self, hint: int = -1, /) -> List[Buffer]: ...
    def seek(self, offset: int, whence: int, /) -> int: ...
    @staticmethod
    def seekable() -> bool: ...
    def tell(self) -> int: ...

class AsyncReadableFile:
    def close(self) -> None: ...
    async def read(self, size: int | None = None, /) -> Buffer: ...
    async def readall(self) -> Buffer: ...
    async def readline(self) -> Buffer: ...
    async def readlines(self, hint: int = -1, /) -> List[Buffer]: ...
    async def seek(self, offset: int, whence: int, /) -> int: ...
    @staticmethod
    def seekable() -> bool: ...
    async def tell(self) -> int: ...
