name: Rust

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Cargo fmt
        run: |
          cargo fmt --all -- --check
          cd pyo3-object_store && cargo fmt --all -- --check && cd ..
          cd pyo3-bytes && cargo fmt --all -- --check && cd ..

      - name: "clippy --all"
        run: |
          cargo clippy --all --all-features --tests -- -D warnings
          cd pyo3-object_store && cargo clippy --all --all-features --tests -- -D warnings && cd ..
          cd pyo3-bytes && cargo clippy --all --all-features --tests -- -D warnings && cd ..

      - name: "cargo check"
        run: cargo check --all --all-features

      - name: "cargo test"
        run: |
          cargo test --all
          cargo test --all --all-features
